### ISSUE TITLE
How to use asciidoctor toc properly

### ISSUE THREAD

**Issue by tortoise74** [asciidoctor/jekyll-asciidoc#135]
Hi,
    I am not quite sure of the proper way to use :toc: with jekyll-asciidoc.
If I have a document Foobar.adoc which starts like this:

<pre>
Foobar
======
:Date: $Date$
:Revision: $Id$
:docinfo:
:toc: left
:page-liquid:
:layout: page
:permalink: /page/
</pre>

It has the useful property that the table of contents is displayed both when the document is converted directly to html with asciidoctor and via jekyll-asciidoc. I don't seem to need to use the tocify filter at all. [I started off with the :toc: by itself before the title in my original asciidoc]
However the toc appears on the left with asciidoctor but not with jekyll. I have tried including the css for an asciidoctor theme from the stylesheet factory but it doesn't seem to make a difference. The .sidebarback (if it is being applied) is not creating a side bar.

What is the correct way to make this happen?

Regards & thanks for creating a very useful system,

Bruce.

**Comment by mojavelinux** [comment]
By default, the Jekyll AsciiDoc plugin converts the AsciiDoc to embeddable HTML...which is basically just the main content. It then inserts that into the page template for your site. You don't get any stylesheets or any other stuff that surrounds or supports that content. That's up to you to provide in your page template. (While it's possible to include the toc in this content, it won't be a sidebar toc).

That's why the tocify_asciidoc filter is required. It let's you place the toc the corresponds to the content anywhere in your page template (outside of the main content). You use this filter *instead of* the toc attribute in your AsciiDoc. This is explained in the following section of the docs: https://github.com/asciidoctor/jekyll-asciidoc#generating-a-table-of-contents

(Note that the tocify_asciidoc is not yet included in an official release. It will be included in 2.1.0.).

If you do just want the Jekyll AsciiDoc plugin to generate standalone HTML output, then you can disable the page layout using `:!page-layout:`. This is described in the following section of the docs: https://github.com/asciidoctor/jekyll-asciidoc#specifying-a-layout

>  The .sidebarback (if it is being applied) is not creating a side bar.

When the HTML generated from AsciiDoc is embedded in a page template, you are responsible for providing all the CSS to style the AsciiDoc components. That's why we provide the following quickstart project. https://github.com/asciidoctor/jekyll-asciidoc-quickstart (It's still a bit rough around the edges, but it should at least get you started on the right path).

**Comment by tortoise74** [comment]
I didn't it this wasn't released yet as some of the discussion about :toc: I googled was quite old. I'll have to check what version I'm using. I installed it using "gem install" so that should be the latest 'release'. Would you consider it suitable for beta yet? I'm happy to be on the bleeding edge (but note I'm new to jekyll and only a recent convert to asciidoc. I wouldn't have gone near ruby for a while yet if the asciidoctor implementation wasn't so vastly beyond the python one).

**Comment by mojavelinux** [comment]
@tortoise74 The latest release is 2.0.1. You can always see the latest release number by looking for the gem badge at the top of the README.

> Would you consider it suitable for beta yet?

The 2.0.1 version is very stable, as is the upcoming 2.1.0 release. If you want to try the 2.1.0 release now, you can follow the instructions in the README. See https://github.com/asciidoctor/jekyll-asciidoc#development. If you need help, don't hesitate to ask.

**Comment by tortoise74** [comment]
Hi,
     I've have a play around but its still not obvious to me. Probably because I'm new to the whole ecosystem. I tried changing the template to:

     <div class="post-content">
       {{ content | tocify_asciidoc }}
     </div>

but this just eliminates the content entirely. I don't know how to get debugging output for that.
Could you perhaps add an example of the quickstart project emulating the behaviour of :toc: left ?

**Comment by mojavelinux** [comment]
First, are you using the latest version from master? (the unrelease 2.1.0 version?)

Second, you shouldn't pass content to the filter...that won't work. You need to pass the parsed document to tocify_asciidoc, as the README describes.

See https://github.com/asciidoctor/jekyll-asciidoc#generating-a-table-of-contents

**Comment by mojavelinux** [comment]
> Could you perhaps add an example of the quickstart project emulating the behaviour of :toc: left ?

I need to release 2.1.0 first.

**Comment by tortoise74** [comment]
I am using the latest version. You are right I failed to rtfm properly. {{ page.document | tocify_asciidoc }} creates a fine toc (at the top of the page before the body of the document).
Now if I use toc2 class that a standalone document using :toc: left would use:

    <div id="toc" class="toc2" >
    {{ page.document | tocify_asciidoc }}
    </div>

I get a perfect sidebar nav but on top of the content rather than to the left of the content.
I am using the golo.css from asciidoc-stylesheet-factory.
I guess this is a matter of hacking the css somehow. Unless there is a more appropriate class to use?

**Comment by mojavelinux** [comment]
Very good!

You also need to add toc2 to the `<body>` element. I recommend studying the HTML structure of the standalone HTML generated by Asciidoctor and try to match that structure using your template. Once you have the same outer structure (aka framing), then the existing styles should work.

**Comment by tortoise74** [comment]
Another thought related to this. I had been considering having a standard jekyll top nav and 'standard' left hand nav from any hosted asciidoc documents. However, I was playing with the lanyon theme (https://github.com/poole/lanyon) which moves that into a hideable left hand sidebar. That makes me think another option is to add the asciidoc toc to the whole site nav. I haven't quite figured that out yet though. Your thoughts are welcome.

**Comment by tortoise74** [comment]
It seems to work very well the lanyon theme has a sidebar.html in its _include dir where I can add:

      <a class="sidebar-nav-item" href="{{ site.github.repo }}">{{ page.title }}</a>
      {{ page.document | tocify_asciidoc }}

Which works quite well.

**Comment by tortoise74** [comment]
Thanks for the help

**Comment by mojavelinux** [comment]
I'm super glad to hear it! Feel free to share an example of your site once it's up.
