### ISSUE TITLE
attributes and hash escaping

### ISSUE THREAD

**Issue by tortoise74** [asciidoctor/jekyll-asciidoc#139]
I think I've founding an interesting corner case with attributes and escaping though it may just be ignorance of the proper escaping rules (in which case please show me where to RTFM)

I have two styles:

    .red {
       color: #ff0000
    }
    .blue {
       color: #0000ff
    }

I wish to render some text as follows:

    #red 
    #blue 
    normal

Now in an asciidoc sandbox.adoc I put:

    [red]##I am red# +
    [blue]##I should be blue but I'm not# +
    I am normal

The first coloured line containing a leading hash comes out red
The second coloured line containing a leading hash does not come out blue.

In the html I get:

    <div class="paragraph">
    <p><span class="red">I am red#<br>
    [blue]</span>I should be blue but I&#8217;m not#<br>
    I am normal</p>
    </div>

This also happens if I try using ## to obtain a hash as in:

    [red]###I am red# +
    [blue]###I should be blue but I'm not# +
    I am normal

If I use \# in the input I get \# in the output.
Another interesting case is:

    [red]#\\## I am red# +
    [blue]#\\## I am blue# +
    I am normal

Which yields one red hash on the first line and two blue hashes on the second line.
I as workaround I do:

    :hash: #

    [red]#{hash} I am red# +
    [blue]#{hash} I am blue# +
    I am normal

Note that http://asciidoctor.org/docs/user-manual/ suggests I should use:

    [rolename]`monospace text`

But the backtick has an effect of its own. 

    [red]`hello world`

comes out as:

    <code class="red">hello world</code></p>

**Comment by mojavelinux** [comment]
There are a few ways to go about this. First, if your content includes a formatting character, then you definitely need to be using the unconstrained formatting at the very least.

```
[red]###I am red## +
[blue]###I am blue## +
I am normal
```

However, visually parsing that is tough. That's why you probably want to either switch to using a character reference for the content part:

```
[red]#&#35;I am red# +
[blue]#&#35;I am blue# +
I am normal
```

or by using an attribute reference:

```
:hash: #

[red]#{hash}I am red# +
[blue]#{hash}I am blue# +
I am normal
```

(You could also set the value of hash to `&#35;` to be safe).

A more brute force approach is to use an inline passthrough, but that should really only be done as a last resort.

```
[red]#++#++I am red# +
[blue]#++#++I am blue# +
I am normal
```

Attributes are very powerful because they allow you to inject content without being interpreted as formatting marks.

**Comment by mojavelinux** [comment]
> But the backtick has an effect of its own.

Yes, backtick is for when you want to make the text monospaced. The hash is for unformatted text (role only).
