### ISSUE TITLE
variable with include macro

### ISSUE THREAD

**Issue by gdolle** [asciidoctor/jekyll-asciidoc#153]
Hi, 

It seems (from my side) that variable substitution does not work when using them in `include::` keyword (it works if I use asciidoctor directly)

```
= Title
:myvar: /path/to

include::{myvar}/file.adoc[]
```

asciidoctor (1.5.5)
jekyll-asciidoc (2.1.0.dev)

(cc @prudhomm)

**Comment by prudhomm** [comment]
I got the same issue in  a source block. The variable is properly substituted but I get unresolved include file

**Comment by prudhomm** [comment]
@mojavelinux any idea ? may be we are missing something ?

**Comment by mojavelinux** [comment]
This should work. Verify that you are using the following settings in _config.yml.

```
asciidoctor:
  base_dir: :docdir
  safe: unsafe
```

Also verify which version of Jekyll you are using.

It would help the most if you pointed me to a sample project that demonstrates the problem.

**Comment by mojavelinux** [comment]
Actually, I see the book site linked. I'll try that.

**Comment by mojavelinux** [comment]
You aren't using asciidoctor-diagram, so you can drop that gem. Also, if you are going to use a dev version, I recommend using a link to github like so:

```ruby
gem 'jekyll-asciidoc', github: 'asciidoctor/jekyll-asciidoc'
```

(you can also link to a specific commit)

**Comment by mojavelinux** [comment]
The problem is asciidoctor-latex. If you disable that gem, you'll see that you can use variables in includes. The likely culprit are the preprocessors that asciidoctor-latex adds. Preprocessors have to be used very carefully, and avoided if possible, because they have side effects. Those side effects are altering how core resolves variables for includes. Without fixing asciidoctor-latex, there's nothing really we can do here in the Jekyll plugin.

**Comment by mojavelinux** [comment]
Specifically, the preprocessor would need to set docdir so that the include is resolved relative to the location of the file. I don't know the specific details as I haven't set up a test, but that's essentially what needs to happen.

**Comment by prudhomm** [comment]
@jxxcarlson what do you think about this ?

**Comment by jxxcarlson** [comment]
I think that @mojavelinux is right.  This is tricky business, because I have had to use pre and post processors to "protect" the math content from changes by asciidoctor.  This is a bad hack whose proper solution is to have a more powerful parser for asciidoc.  The problem there is that asciidoc, like markdown (and also latex) is not governed by a context-free grammar.  This makes parser design difficult.  Alas, I don't think there is a quick solution, though I'm certainly willing to look at the pre and post processors again.

**Comment by mojavelinux** [comment]
While a more powerful parser will always make for better solutions...it's not impossible to accomplish this today.

I don't think extensions should use preprocessors as it changes the behavior of the parser. They should be reserved for custom user code. Instead, treeprocessors should be used. asciidoctor-mathematical has used them to great effect. They have the full access to the block AST, but can't still perform substitutions inline before the normal substitutions get applied. (They are still far from perfect, but they are workable).

There is a way to use a preprocessor without getting too many unintended side effects, but it requires reading and parsing the header, extracting all the resolved attributes, then starting over and reading the rest of the document. I have some prototype code for this in the coalescer script. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb.

**Comment by mojavelinux** [comment]
> but it requires reading and parsing the header, extracting all the resolved attributes, then starting over and reading the rest of the document.

The reason this is necessary is because the document header affects how the preprocessor is behaves. So you have to do a bit of parsing before you allow the reader to continue.

**Comment by prudhomm** [comment]
@jxxcarlson here is the website where asciidoctor-latex is heavily used !

http://book.feelpp.org/math/fem/

and the `.adoc` files which were initially obtained from `.tex` using pandoc are here

https://github.com/feelpp/book.feelpp.org/tree/master/docs/math/fem

here is a sample use
https://raw.githubusercontent.com/feelpp/book.feelpp.org/master/docs/math/fem/ch-ef-lagrange.adoc

I (or people from my team) would like also to contribute because we need to be able to write advanced math.

**Comment by djencks** [comment]
Roughly speaking, preprocessor extensions and include:: are incompatible.  This is a fundamental part of Asciidoctor and not anything jekyll-asciidoc has any control over.
