### ISSUE TITLE
docinfo support?

### ISSUE THREAD

**Issue by bartvanderwal** [asciidoctor/jekyll-asciidoc#164]
I found out about `docinfo` in the asciidoctor manual:
http://asciidoctor.org/docs/user-manual/#docinfo-file

So I tried adding a `docinfo.html` to get something inserted in the `<head>` of a file. But it didn't work. Is this supported in jeyll-asciidoc?

**Comment by mojavelinux** [comment]
I don't think docinfo really makes sense in the context of Jekyll AsciiDoc (unless you're producing standalone files generated by Asciidoctor). The typical use of Asciidoctor inside of Jekyll is to produce embeddedable HTML (basically the article part of the page). You then use Jekyll to apply a layout to that HTML. And that's where all the framing / shell material goes.

In other words, you don't need docinfo in Jekyll because you have layouts.

If you happen to be using Jekyll to manage calling Asciidoctor on a handful of pages, and those are produced as standalone pages by Asciidoctor, then you might need docinfo. In that case, it will work, but you do have to set the base_dir to docdir as explained in https://github.com/asciidoctor/jekyll-asciidoc#specifying-the-base-directory. That way, Asciidoctor can find the docinfo file.

**Comment by mojavelinux** [comment]
I just realized something. It's not that docinfo doesn't make sense. It's that it just needs to be called at a different time.

What we could do is add a liquid tag called asciidoc_docinfo that invokes the Document#docinfo method. You'd use this tag in your liquid template, but it would tie back into the docinfo functionality of the processor. It's very similar to what tocify_asciidoc is doing.

**Comment by djencks** [comment]
I implemented this.
The simplest implementation allows you to specify any location you want, and include suitably named content from docinfo files, anywhere you want.
Should this be restricted so the only accepted locations are (nil), 'head', and 'footer'?

**Comment by mojavelinux** [comment]
I think it should at least be head, header, and footer. If more locations are supported, it should be clearly documented that these are non-standard, so they will likely only work with this converter.

**Comment by djencks** [comment]
Thanks!
Does jekyll convert to docbook?  If not, does 'header' make sense as standard?
I like the idea of allowing anything and clearly documenting that only head, footer, and possibly header will work outside jekyll.

**Comment by mojavelinux** [comment]
The official locations are head, header, and footer, which are all supported by the built-in HTML converter.

> Does jekyll convert to docbook?

Not currently, though if there's a compelling case for it, it would certainly be possible.

> If not, does 'header' make sense as standard?

Yes, I believe it does.

**Comment by djencks** [comment]
Ah, I missed the call with :header in the html5 converter.  I had thought html used head and footer, and docbook header and footer.

**Comment by mojavelinux** [comment]
There used to be only two locations (header and footer), but we expanded it since there are really 3 logical locations at a minimum.

**Comment by djencks** [comment]
This is open for review, I'm happy with the implementation.
