### ISSUE TITLE
excerpt is always empty

### ISSUE THREAD

**Issue by maxandersen** [asciidoctor/jekyll-asciidoc#200]
not sure if this is jekyll-asciidoc or something else but I've noticed that .adoc posts *alwways* have an empty post.excerpt. my old .md files have the expected .excerpt - any idea why ?

**Comment by mojavelinux** [comment]
Currently, it's necessary to define the excerpt as follows:

```
= Post With Excerpt
:page-excerpt: This is the _excerpt_ of this post.

Lorem ipsum.
```

This signals to Jekyll AsciiDoc that it can process the excerpt as AsciiDoc.

Excerpts are designed in such a way that the plugin code has no idea where they came from (we don't know whether it's a Markdown or AsciiDoc file). As a result, it's not clear what filter to apply to them.

Now that we're moving to Jekyll 3, we may have the necessary hooks now to address this problem, or we can file an issue upstream to make more information available.

**Comment by mojavelinux** [comment]
As it stands now, the excerpt separator (which is what is used in Markdown posts) only grabs the AsciiDoc header, and from there tries to find a body to split. That explains why the value is always blank.

But the reason we haven't fixed it yet is because we need to solve the first problem I cited. So this is both a bug and an enhancement ;)

**Comment by maxandersen** [comment]
hmm - so setting a more explcit excerpt marker could do the trick ?

**Comment by mojavelinux** [comment]
I did some analysis and I think this can be done, but it's going to require a lot of thinking and some custom code. The place where excerpts are extracted in Jekyll makes it extremely difficult to extend. But it doesn't mean it's impossible.

**Comment by mojavelinux** [comment]
> page.excerpt always contains the whole document, which isn't nice either.

It's a bit more complicated than that. Jekyll AsciiDoc tries to extract a header. If it can't find one, it uses the whole document. Depending on how your excerpt separator is set, this could result in the excerpt being the whole document.

**Comment by mojavelinux** [comment]
I think I've got a solution for this. I'm working on cleaning up the prototype and writing some tests so I can push it.

**Comment by mojavelinux** [comment]
At long last, I have sent the PR. See #213.

If you are currently using excerpts, this will introduce a breaking change. That's because excerpts now self convert to HTML, so you no longer need to pipe them to asciidocify. This makes them consistent with the way excerpts are handled for Markdown pages.

**Comment by maxandersen** [comment]
better late than never but I finally got my blog updated to utilize this and just want to say thank you! One more place I could get markdown removed :)

**Comment by mojavelinux** [comment]
Fantastic news! Congrats! :rocket:

**Comment by Stratus3D** [comment]
Echo what @maxandersen said! Thanks for making these changes! I now have nice "read more" links for my Jekyll blog, and the newsletter that I generate from it!
