### ISSUE TITLE
How to pass asciidoctor command line options such as --verbose and --failure-level?

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/jekyll-asciidoc#220]
I would like to see if I have broken xrefs.

Any way to set this? If it were possible to set as a document attribute, that would also be a solution, but I couldn't find it.

Another option for `--verbose` would be to map the `jekyll build --verbose` to it, but apparently this is not done.

Tested with: https://github.com/cirosantilli/jekyll-min/tree/63fc5cac2f8de5905a296387c20143b7004d3c2f

**Comment by mojavelinux** [comment]
Commandline options aren't relevant in this context since Asciidoctor is called via the API, not the CLI.

The API options can be specified here: https://github.com/asciidoctor/jekyll-asciidoc#asciidoctor

The Asciidoctor API doesn't currently support changing the logger or verbose mode. That would be needed in this context, or else the integration would have to handle that itself.

**Comment by mojavelinux** [comment]
> The Asciidoctor API doesn't currently support changing the logger or verbose mode.

The assumption is that the code that invokes the API takes care of it.

**Comment by cirosantilli** [comment]
Thanks Dan, canyou exemplify how to set --verbose specifically?

**Comment by cirosantilli** [comment]
Ooops, sorry, now I read properly. Thanks for the reply!

**Comment by djencks** [comment]
As of 2.0.0 Asciidoctor logging is fed into Jekyll logging, so I would expect all that's needed is to configure the log levels in both.  Perhaps they should be synchronized or the Asciidoctor level exposed to configuration.  I haven't tried anything yet.
