### ISSUE TITLE
Difficult to use pygments classes

### ISSUE THREAD

**Issue by amr** [asciidoctor/jekyll-asciidoc#30]
Hi,

Jekyll by default uses pygments, and ships with a `_syntax-highlighting.scss` file. With this configuration...

```yaml
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
```

... syntax highlighting doesn't work. The reason is that `asciidoctor` uses [a custom `tok-` class prefix](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/stylesheets.rb#L74). So all pygments stylesheets do not work by default and must be modified to include the `tok-` prefix.

Is it possible to tell asciidoctor to not use that prefix?

**Comment by mojavelinux** [comment]
Interesting, I wasn't aware that Jekyll shipped with a Pygments stylesheet.

As you noticed, Asciidoctor hardcodes the `tok-` prefix to avoid clashes in class names. I agree this should probably be configurable. Fortunately, there are two workarounds.

(a) First, you can instruct Asciidoctor to inline the styles for Pygments using the setting `pygments-css=style` (the default is `pygments-css=class`). The downside with this approach is that you are stuck to colors from the default theme in this case.

(b) Second, you can use Asciidoctor to write the Pygments stylesheet instead of using the one provided by Jekyll. You can do this by calling the following API:

```ruby
Asciidoctor::Stylesheets.instance.write_pygments_stylesheet '_site/css', 'pastie'
```

Then, include that stylesheet (e.g., css/pygments-pastie.css) in your main template.

Note the using Asciidoctor's version is important because it provides the necessary styles to override AsciiDoc styling. It's tricky because everyone wants to be king when it comes to styles ;)

Perhaps this is something that could be handled by the Jekyll AsciiDoc plugin transparently. Thoughts?

**Comment by robjens** [comment]
I agree, in my book this definitely falls in the current category of 'not easy enough as it should be'. Coderay works out of the box, but Pygments stylesheet is missing from the jekyll-asciidoc (quickstart) project as well - one might guess that from your surprise to find Jekyll shipped with it, out of the box.

Possible course of action would be to include this (`Asciidoctor::Stylesheets` logic) in the `jekyll-asciidoc` plugin. I'm not sure what you mean by

> Note the using Asciidoctor's version is important

I mean, I get what you are saying but there is no mention in your or TS post about version number is there? (I could be overlooking). A `_config.yml` (and document level) special treatment of pygments style variable(s) could deal with with the output location and prefered theme. That or just include the already converted asciidoctor pygments stylesheets? I mean, usually the number of themes doesn't supersede a dozen or so does it? Couldn't they just be included with the plugin, and copied over at Jekyll build time according to a specified location? Or is there some aspect of dynamic class/style names involved that I'm unaware of? Currently don't have that impression.

Anyway, my Ruby is a little rusty and I really don't know the Jekyll API much, but I'll take a shot at hacking in a method for this in the jekyll-asciidoc plugin since I have the repo for building from source anyway.

**Comment by robjens** [comment]
@amr What do you mean by 'by default'. I tried `jekyll new foo`, I'm pretty sure i have the latest running. I did a `ag pygments` in that folder, not a trace.

**Comment by mojavelinux** [comment]
> We could just add these to the (quickstart) project and be done with it. 

Sounds reasonable to me. The CodeRay stylesheet was added just because that was Jared's preference, but I think the project should provide both for parity.

**Comment by robjens** [comment]
Sorry for the late response. I'll have another look at this and submit a pull request if it hasn't been done yet. Thanks for the feedback.

**Comment by mojavelinux** [comment]
> (a) ... The downside with this approach is that you are stuck to colors from the default theme in this case.

Actually, I misspoke. Including the styles inline does still honor the theme.

**Comment by mojavelinux** [comment]
The integration with Pygments in Asciidoctor really calls for the Pygments stylesheet that Asciidoctor generates (which is backed by the Pygments API, making all the themes in Pygments available). Therefore, I've decide to auto-generate the CSS file into the `stylesdir` of the source directory if the attributes in the site configuration are configured as follows:

* `source-highlighter` has the value `pygments`
* `pygments-css` does not have the value `style`
* `pygments-stylesheet` does not have the value `nil` (meaning it is not unset)

By default, the stylesheet is written to `stylesdir` + `pygments-stylesheet`. If `pygments-stylesheet` is not set (and not unset), it defaults to `asciidoc-pygments.css`.

The file will be written if it does not exist or the contents have changed. The Pygments theme is selected by the value of the `pygments-style`. If this attribute is not set, it defaults to `pastie`.

The file will then get copied to the output directory by Jekyll.

**Comment by mojavelinux** [comment]
You'll be able to disable this feature in one of two ways. First, you can switch to inline styles:

```yaml
asciidoctor: 
  attributes:
    - pygments-css=style
```

Or you can disable the pygments-stylesheet attribute:

```yaml
asciidoctor:
  attributes:
    - pygments-stylesheet!
```
