### ISSUE TITLE
publishing Jekyll 3 updates

### ISSUE THREAD

**Issue by chrylis** [asciidoctor/jekyll-asciidoc#36]
A fix for Jekyll 3 compatibility was merged several months ago, but the version available on rubygems.org does not have it. Is there a timeline for deploying the fixed version?

**Comment by mojavelinux** [comment]
@paulrayner are you available to make a new release? Perhaps name it 1.0.1? Let me know if you need any assistance.

**Comment by paulrayner** [comment]
Yes. I'll take care of it this week.

Paul.

**Comment by mojavelinux** [comment]
Great! Thanks @paulrayner! I'm hear if you need me.

**Comment by paulrayner** [comment]
Running late on this due to other commitments last week. I'll get to it as
soon as I can.

Paul.

**Comment by mitzimorris** [comment]
just ran into this problem:

/var/lib/gems/2.1.0/gems/jekyll-asciidoc-1.0.0/lib/jekyll-asciidoc.rb:84:in `generate': undefined method `getConverterImpl'

jekyll 3.0.0
running on a docker image,  install instructions in Dockerfile are:

RUN export DEBIAN_FRONTEND=noninteractive TERM=linux && \
  apt-get -y install ruby ruby-dev nodejs && \
  gem install asciidoctor jekyll jekyll-asciidoc

**Comment by antonmoiseev** [comment]
Sorry not familiar with ruby at all, is there a workaround to run the pre release version? Install directly from a git repo or anything else?

**Comment by mojavelinux** [comment]
Just clone the repository and run `rake install`. That will build and install the gem.

**Comment by antonmoiseev** [comment]
ah, thanks, didn't realise the development version will be installed globally. However I had an issue running this command:

```sh
$ rake install
rake aborted!
Don't know how to build task 'install'
```
I didn't have the bundler installed, it caused the issue. This is probably should be a part of the installation guide, but don't know where would be the right place to add it, since it may be required by other installation options.

**Comment by mojavelinux** [comment]
Bundler is pretty much required these days anywhere you use Ruby. However, to help developers along who don't already have it installed, I've added instructions to the Rake build if Bundler fails to load:

```
jekyll-asciidoc: Bundler is required to build this gem.
You can install Bundler using the `gem install` command:

 $ gem install bundler
```

**Comment by mosabua** [comment]
Would be great to get a new release out supporting Jekyll 3 ... otherwise requires some hackery to just get this going.

**Comment by eshepelyuk** [comment]
Hello, is there any chance to get `Jekyll3` support released soon ?

**Comment by mojavelinux** [comment]
@eshepelyuk, if you and @paulrayner agree, I'd be happy to add you as a maintainer of the gem so that you can share the responsibility of publishing the gem when needed.

**Comment by mkobit** [comment]
I am interested in trying out Jekyll 3 and AsciiDoctor together, but it doesn't look like this has been completed yet. I'm not familiar with Ruby publishing, but is all that is needed is for somebody to package and publish a new version?

**Comment by mojavelinux** [comment]
Yes, we are looking for someone to take on the responsibility of publishing releases to RubyGems.org. Even better if that could be more automated, but I'd be happy with having a release engineer doing it manually in the short term. If it comes down to it, I'd consider doing it, but with many other projects to release, I don't want to become a bottleneck.

**Comment by mkobit** [comment]
**Note**: To preface this, I know little about Bundler, Ruby, Rake, and Gems.

I took a look at what it would take to manually release this, and everything seems pretty straightforward. Most of this is documented in the [README](https://github.com/asciidoctor/jekyll-asciidoc/blob/master/README.adoc#releasing-the-gem-to-rubygems-org), but I'll list out the steps to make sure I'm not misinterpreting or missing something.

1. Get push access to _asciidoctor/jekyll-asciidoc_ (this repository)
1. Set version in _lib/jekyll-asciidoc/version.rb_ to `1.0.1`
1. Commit change with release note -> `git add lib/jekyll-asciidoc/version.rb && git commit -m "Release 1.0.1"`
1. Get permission from one of the maintainers to publish new version to RubyGems
1. Run `rake release` (most of the magic happens here)
1. Set version in _lib/jekyll-asciidoc/version.rb_ to `1.0.2.dev`
1. Commit change with dev note -> `git add lib/jekyll-asciidoc/version.rb && git commit -m "Being development on next release"`
1. Push up commits and tag to _asciidoctor/jekyll-asciidoc_ -> `git push --follow-tags`

I would be willing to do this now since this has sat around for some time, and it is seems straightforward. I'm not sure if I would really be that comfortable being a maintainer of this, due to my unfamiliarity with the Ruby ecosystem.

I'd really like to see this new version get published soon so that users, including me, can start using AsciiDoc with Jekyll 3 without having to build this locally.

I'm not as concerned about automating the release of this package right now because the last commits were in December, but I think that would be interesting to look at. A lot of the work is currently done by the `rake release` task, but I would think that would need to change somewhat in order to deal with automation. Possibly have TravisCI/CircleCI to build and push gem on tag here, or just automatically release a new patch version on each change? I'm not as sure about that part.

**Comment by mojavelinux** [comment]
@mkobit You have a crystal clear understanding of what needs to be done. Nice summary!

First things first, in order to do the release, you'll need an account on RubyGems.org. Add a comment to this issue with your username once you've created one.

I only have one correction to the steps you identified. I don't think (8) is necessary. I'm pretty sure that `rake release` pushes the tags. But it doesn't hurt to run `git push` again since it won't duplicate anything it's already done.

I'd also like to see a corresponding release page on GitHub. This is done by navigating to the "release" tab and clicking the "Draft a new release" button. Select the tag and enter the same value in the title field. Then, add a few bullet points about what changed from the git log.

    $ git shortlog v1.0.0..v1.0.1

Just pick out the notable stuff, namely references to issues.

(See https://github.com/asciidoctor/asciidoctorj/releases for ideas about what other information to add, though keep in mind it doesn't need to be that complex for now).

>  A lot of the work is currently done by the rake release task, but I would think that would need to change somewhat in order to deal with automation.

Exactly. Let's create a separate issue to track it. Ideally, `rake release` should do everything in your list. It will require encoding an API key into the Travis CI build so that it can push the gem to RubyGems.org. This will not only help this gem, but every gem in the Asciidoctor ecosystem.

I think I speak for everyone when I say that we appreciate you stepping up to the plate. Don't worry about being alone on this because, at the very least, I'm here to assist. This certainly isn't a life-long commitment :) We'll take it one release at a time.

**Comment by mkobit** [comment]
RubyGems handle: **mkobit**

**Comment by paulrayner** [comment]
To add new owners on RubyGems, it looks like I need to do 'gem owner jekyll-asciidoc -a {email-addr}'. Seems like gem ownership is based on email address rather than Rubygems account name based on http://guides.rubygems.org/command-reference/#gem-owner. Is that right? If so, I'll need email addresses to add new owners.

**Comment by paulrayner** [comment]
Done: 
![image](https://cloud.githubusercontent.com/assets/98950/13900288/695eda10-edc8-11e5-9c0e-7dc2f413e724.png)

**Comment by mojavelinux** [comment]
Thanks @paulrayner! We're ready to roll. @mkobit, feel free to proceed and let me know if you need a hand with anything.

**Comment by mkobit** [comment]
`1.0.1` has been [published to RubyGems](https://rubygems.org/gems/jekyll-asciidoc/versions/1.0.1). I added a version badge to the README from https://badge.fury.io/, but it doesn't look like it has picked up the new version yet.

I wrote up [release notes](https://github.com/asciidoctor/jekyll-asciidoc/releases/tag/v1.0.1) and linked to a few different PRs and issues - most of the commits were related to documentation and Jekyll 3.0.

**Comment by mojavelinux** [comment]
Amazing work Mike! We all thank you!

I switch the badge to shields.io, which resolved the version problem. We tend to prefer shields.io in the Asciidoctor ecosystem.

**Comment by mojavelinux** [comment]
@mkobit would you like to open a new issue to track automating the release from CI? Here's the matching issue in Asciidoctor core. https://github.com/asciidoctor/asciidoctor/issues/1565
