### ISSUE TITLE
How to enable diagram generation

### ISSUE THREAD

**Issue by eshepelyuk** [asciidoctor/jekyll-asciidoc#41]
Hello,

Is there a way of enabling diagram generation for `AsciiDoctor` pages in `Jekyll` ?

Durig startup I am receiving following warning 

     $ asciidoctor: WARNING: <stdin>: line 8: invalid style for literal block: ditaa

Though I am able to generate HTML with embedde `Ditaa` diagram by calling 

    $  asciidoctor -r asciidoctor-diagram sample.adoc 

I assume that `asciidoctor-diagram` is not _required_ by plugin, but is there a way of _requiring_ this module ?

I'm still using `Jekyll 2.5.x` and `jekyll-asciidoc 1.0.0`

**Comment by mojavelinux** [comment]
I think you just need to add it to the Jekyll configuration.

With bundler, add it to Gemfile:

```
group :jekyll_plugins do
  gem 'asciidoctor-diagram'
end
```

Without bundler, add it to _config.yml:

```
gems:
  - asciidoctor-diagram
```

That should do it. You can configure the location where the diagrams are generated using the AsciiDoc attribute `imagesoutdir`.

```
asciidoctor:
  attributes:
    - imagesdir=/images
    - imagesoutdir=images
```

However, the images don't seem to get copied the first time you run Jekyll because they are generated too late. It also doesn't handle all the cases...you'll need to do some experimentation with paths. Some hacking on the plugin may be required.

Alternatively, you can use `data-uri` to embed the images. This works every time because it doesn't need to get any paths right. You will might want to set `imagesoutdir` in the configuration so that the temporary files aren't generated in the root folder (or even inside the project, in which case you have to set the `safe` option to `unsafe`).

**Comment by mojavelinux** [comment]
In short, the biggest challenge here is getting the paths right, but that's a general problem right now when using Asciidoctor Diagram inside a build tool or static site generator.

**Comment by eshepelyuk** [comment]
Thank you, diagram generation started working after adding `Gem` to `bundler` `Gemfile`, problem with path exists :)

Would you mind adding this information (about enabling diagrams) to `README` ?

**Comment by mojavelinux** [comment]
Definitely. This would be very valuable information for the README. Would you like to send a pull request with a new section?

As for the path issue...that's going to require a bit more research and fiddling.

**Comment by eshepelyuk** [comment]
Sure, I will create a PR regarding `README` update in a while.

**Comment by mojavelinux** [comment]
Thanks @eshepelyuk!

**Comment by eshepelyuk** [comment]
Created PR #42
