### ISSUE TITLE
Release 1.1.1

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/jekyll-asciidoc#58]
I think we're ready for another release. This release introduces some differences to how the plugin works enough to warrant at least a bump to the minor release number.

The most important changes are as follows:

* The AsciiDoc document title overrides the title set in the front matter or the title that's automatically generated (in the case of a post)
* The AsciiDoc page-related attributes override the matching entries in the page data (i.e., front matter)
* The value of page-related attributes are treated as YAML values (automatic type coercion)
* page- is the default prefix for page-related AsciiDoc attributes (e.g., `page-layout`).
* The key to configure the page attribute prefix is `asciidoc_page_attribute_prefix`; the value should not contain the trailing hyphen
* The date of a post can be set using the `revdate` AsciiDoc attribute
* Only configure the Asciidoctor options once (previously it was being called twice in serve mode)

@mkobit would you like to do the release?

**Comment by mojavelinux** [comment]
Before we release, I'd like to collect feedback from people who are using the plugin to ensure we haven't broken anything unexpectedly. cc: @eshepelyuk @johncarl81 @mkobit @paulrayner

**Comment by mkobit** [comment]
Sure, I'll do the next release. 

I'm still not making extensive use of the plugin, so it would be awesome if others mentioned could chime in to see if it breaks anything.

Do you think it makes sense to do a 'prerelease' type version (like a `1.1.0.alpha.1`) so it is easier for others to consume and verify?

**Comment by eshepelyuk** [comment]
Please, do next release.

**Comment by mojavelinux** [comment]
> Do you think it makes sense to do a 'prerelease' type version 

Good question. I'm certainly open to making a candidate release. I'd call it `1.1.0.rc.1`. I think we're past an alpha at this point :)

**Comment by mkobit** [comment]
I made a mistake while trying to release `1.1.0`. I accidentally ran `bundler exec rake release` from personal branch that was pointing to my forked remote which was not updated, when I thought it was pointing to this remote. I guess this is what happens when a tired meatbag does it :neutral_face: . This is another good reason for me (or someone else) to dive into https://github.com/asciidoctor/jekyll-asciidoc/issues/45

I ran `gem yank jekyll-asciidoc -v 1.1.0` immediately after, but it does not look like there is a grace period to have a 'do-over' and republish as `1.1.0`. You can see the unfortunate mistake [on my fork](https://github.com/mkobit/jekyll-asciidoc/commits/master).

I (originally) decided to forgo the RC style release, as I thought if there were any issues we could just bump the version again if any issues popped up. Maybe next time I'll stick to using the RC process, or  try to tackle the 1-click or 0-click release so this ca

`1.1.1` is available on [RubyGems](https://rubygems.org/gems/jekyll-asciidoc/versions/1.1.1) right now. I haven't written up the release notes yet, as the milestone is currently marked as `v1.1.0`. @mojavelinux , what do you think the best thing close this out, and also steps to avoid this in the future?

**Comment by mojavelinux** [comment]
No problem, @mkobit. We live and learn. That's part of the process. Trust me, I don't get every gem release right the first time either.

First, thanks for releasing 1.1.1! I went ahead and deleted the v1.1.0 tag so there is no confusion.

For the future, I'd recommend a few things.

1. Add anything you learned to the release instructions; a pre-release checklist is a handy tool
2. Plan to add validation to our automated release task; for instance, it can verify assumptions such as the local branch name
3. Using a release candidate is a helpful way to make a practice release, esp after being away for awhile, before committing to the stable release number; that said, a good automated release task should provide a safety net.

> I ran gem yank jekyll-asciidoc -v 1.1.0 immediately after, but it does not look like there is a grace period to have a 'do-over' and republish as 1.1.0.

This is good information for the release instructions.

**Comment by mojavelinux** [comment]
Oh, and I updated the milestone to v1.1.1. We just won't have a v1.1.0 :)
