### ISSUE TITLE
Includes are relative to Jekyll execution directory

### ISSUE THREAD

**Issue by magi42** [asciidoctor/jekyll-asciidoc#80]
While you normally have a website where each ADoc file is converted to one HTML page, sometimes you want to split up a big ADoc file. However, it seems that if you have an `include::` directive in an ADoc file, the include path is handled relative to the directory where Jekyll is executed, not the path of the ADoc file. Therefore, relative paths in include directives don't work like they should.

For example, if I have master document at:

```
website/_mypages/somepath/tutorial.adoc
```

Then I have there an include such as:

```
include::tutorial/intro.adoc[]
```
When I start `jekyll serve` in the `website` directory, I get error such as:

```
include file not found: /.../website/tutorial/intro.adoc
```

While it should try to get it from `.../website/_mypages/somepath/tutorial/intro.adoc`.

Looking at the plug-in sources, it looks that the ADoc converter only gets the page content as its input and doesn't know anything about its location.

It would be OK to have the current file path even in an attribute, but of course best if it behaved properly.

**Comment by mojavelinux** [comment]
I'm glad you brought this up. We're not yet managing the base_dir in this plugin, as we should be. I'm going to try to implement the same behavior that I did for the Middleman integration. Basically, the base_dir will be set to the document directory by default (the normal way that Asciidoctor works). I'll also make it possible to set the base_dir to the source directory or the project root.

It might also be helpful to pass in some of the site config as attributes such as `site-source`, `site-dest` and `site-baseurl` and others.

**Comment by mojavelinux** [comment]
I have sent an initial PR for base_dir support (see #83). It will only work in Jekyll 3 since we need to leverage the `:pre_render` hook.

Here's how you would define your config so that includes are resolved relative to the document:

```yaml
asciidoctor:
  base_dir: :docdir
```

`:docdir` is a special keyword that means the base_dir should follow the directory of the document (updated dynamically).

There is one snag that we've hit that traces back to an old issue in Asciidoctor. It's not possible to set the base_dir (the jail) separate from the docdir (the root from which includes are resolved). Therefore, if you need to include a file in a directory above the current file, you must set the safe mode to `unsafe` (which doesn't enforce the jail). Eventually, we want to decouple base_dir and docdir so that the jail can be different from the file root. This issue is a reminder of that ;)

**Comment by magi42** [comment]
Excellent, that was quick, thanks! We now switched to the latest jekyll-asciidoc, I tried it and it seems to do the job. We found a possible way to do it with Liquid, although that didn't work very nicely.
