### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/jekyll-asciidoc#96]
As soon as all other issues are closed for milestone ~~v1.2.0~~ v2.0.0, we'll be ready for another release of this gem.

This release comes with a lot of changes, including dropping support for Jekyll 1, making the front matter header optional, parsing page attributes values as YAML data, restructuring the configuration keys, allowing pages to be generated as standalone HTML documents (not using a layout from the site) and allowing the base directory to track the document directory.

The big question is whether we should name this release 1.2.0 or 2.0.0. I've done my best to maintain backwards compatibility, but the manner in which pages are created has still changed substantially. I think that warrants a major release. Any thoughts?

**Comment by sboekhoff** [comment]
If there is at least one file that cannot be converted with the new version or one configuration that does not work anymore, the new version should be `2.0.0`. Otherwise it's just adding features (Deprecating functionality is (in my opinion) not a reason to raise the major level).

You mentioned, that Jekyll `1.x.x` is not supported anymore. Thus, users have to switch to `2.x.x` or `3.x.x` and hence might also have to touch their files. In this case the new version should definitely be `2.0.0`.

For me a change in the major level is a hint that I might have to change files to keep everything running.

**Comment by mojavelinux** [comment]
I can't say for absolute certainty whether there are any files that will not convert with the new version, but I can say that it is at least a risk. I think your terms make it clear that this should be named 2.0.0.

**Comment by mojavelinux** [comment]
I think we should increase the minimum version of Jekyll from 2.0.0 to 2.3.0. I propose that because most people seem to be on 2.5 at a minimum and 2.3.0 was when many of the APIs in Jekyll changed. In particular, we can't make the front matter header optional for Jekyll < 2.3.0 because the method that we need to override is in a different location. Bumping the minimum version to 2.3.0 would simplify the documentation. wdyt?

**Comment by sboekhoff** [comment]
Since it is a major release I think it's perfectly fine.

**Comment by mojavelinux** [comment]
Let's do it!

**Comment by mojavelinux** [comment]
Okay, 2.3.0 is now the minimum version of Jekyll the plugin permits.

**Comment by mojavelinux** [comment]
Released! See https://github.com/asciidoctor/jekyll-asciidoc/releases/tag/v2.0.0.

@mkobit I went ahead and did this release since I had done so much development on it and I wanted to collect more notes about the release procedure.
